version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_DATABASE: "begonia-test"
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - 2379:2379
      - 2380:2380
    restart: always
    container_name: etcd

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z
    container_name: minio
    command: server --console-address ":9001" /data
    ports:
      - ${MINIO_PORT}:9000
      - 9001:9001
    env_file:
      - ./.env
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - TZ=${TIMEZONE}
    restart: always