// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: endpoint.proto

package v1

import (
	context "context"
	v1 "github.com/begonia-org/begonia/common/api/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EndpointService_Create_FullMethodName = "/begonia.org.begonia.EndpointService/Create"
	EndpointService_Update_FullMethodName = "/begonia.org.begonia.EndpointService/Update"
	EndpointService_Delete_FullMethodName = "/begonia.org.begonia.EndpointService/Delete"
	EndpointService_List_FullMethodName   = "/begonia.org.begonia.EndpointService/List"
)

// EndpointServiceClient is the client API for EndpointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndpointServiceClient interface {
	Create(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*v1.APIResponse, error)
	Update(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*v1.APIResponse, error)
	Delete(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*v1.APIResponse, error)
	List(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*v1.APIResponse, error)
}

type endpointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointServiceClient(cc grpc.ClientConnInterface) EndpointServiceClient {
	return &endpointServiceClient{cc}
}

func (c *endpointServiceClient) Create(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*v1.APIResponse, error) {
	out := new(v1.APIResponse)
	err := c.cc.Invoke(ctx, EndpointService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointServiceClient) Update(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*v1.APIResponse, error) {
	out := new(v1.APIResponse)
	err := c.cc.Invoke(ctx, EndpointService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointServiceClient) Delete(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*v1.APIResponse, error) {
	out := new(v1.APIResponse)
	err := c.cc.Invoke(ctx, EndpointService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointServiceClient) List(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*v1.APIResponse, error) {
	out := new(v1.APIResponse)
	err := c.cc.Invoke(ctx, EndpointService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndpointServiceServer is the server API for EndpointService service.
// All implementations must embed UnimplementedEndpointServiceServer
// for forward compatibility
type EndpointServiceServer interface {
	Create(context.Context, *EndpointRequest) (*v1.APIResponse, error)
	Update(context.Context, *EndpointRequest) (*v1.APIResponse, error)
	Delete(context.Context, *EndpointRequest) (*v1.APIResponse, error)
	List(context.Context, *EndpointRequest) (*v1.APIResponse, error)
	mustEmbedUnimplementedEndpointServiceServer()
}

// UnimplementedEndpointServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEndpointServiceServer struct {
}

func (UnimplementedEndpointServiceServer) Create(context.Context, *EndpointRequest) (*v1.APIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEndpointServiceServer) Update(context.Context, *EndpointRequest) (*v1.APIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedEndpointServiceServer) Delete(context.Context, *EndpointRequest) (*v1.APIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedEndpointServiceServer) List(context.Context, *EndpointRequest) (*v1.APIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedEndpointServiceServer) mustEmbedUnimplementedEndpointServiceServer() {}

// UnsafeEndpointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndpointServiceServer will
// result in compilation errors.
type UnsafeEndpointServiceServer interface {
	mustEmbedUnimplementedEndpointServiceServer()
}

func RegisterEndpointServiceServer(s grpc.ServiceRegistrar, srv EndpointServiceServer) {
	s.RegisterService(&EndpointService_ServiceDesc, srv)
}

func _EndpointService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).Create(ctx, req.(*EndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).Update(ctx, req.(*EndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).Delete(ctx, req.(*EndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).List(ctx, req.(*EndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EndpointService_ServiceDesc is the grpc.ServiceDesc for EndpointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EndpointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "begonia.org.begonia.EndpointService",
	HandlerType: (*EndpointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EndpointService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EndpointService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EndpointService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _EndpointService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "endpoint.proto",
}
