endpoints:
  proto:
    makefile: "/data/work/begonia-org/begonia/internal/pkg/runtime/Makefile"
    gomod: "/data/work/begonia-org/begonia/go.mod"
    wd: "/data/work/begonia-org"
  plugins:
    dir: "/data/work/begonia-org/begonia/plugins"
file:
  upload:
    dir: /data/work/begonia-org/begonia/upload
  engines:
    - name: "FILE_ENGINE_MINIO"
      endpoint: "127.0.0.1:9000"
      accessKey: "7OdVJK1alV8cpRMeBLBW"
      secretKey: "2GNNRqqElReC1KnV3kX9jSjyLU4kwOaTZEqDS2vH"
    - name: "FILE_ENGINE_LOCAL"
      endpoint: "/data/work/begonia-org/begonia/upload"
  protos:
    dir: /data/work/begonia-org/begonia-go-sdk/protos
    desc: /data/work/begonia-org/begonia-go-sdk/protos/api.bin
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "test"
  password: "test"
  database: "begonia-test"
  table_prefix: "begonia_"
admin:
  name: "admin"
  password: "admin"
  email: "admin@example.com"
  phone: "12345678901"
auth:
  aes_key: "1234567890123456"
  aes_iv: "L!#x].upV.>Jx0QN"
  jwt_secret: "WNjp6mW^GXnRf3]34asF"
  jwt_expiration: 7200 # seconds
  rsa:
    private_key: "/data/work/begonia-org/begonia/cert/auth_private_key.pem"
    public_key: "/data/work/begonia-org/begonia/cert/auth_public_key.pem"
  blacklist:
    filter:
      entries: 100000
      error_rate: 0.01
    pubsub:
      channel: "gateway-blacklist"
      group: "gateway-blacklist-group"
    user:
      cache_expire: 3600 # seconds
  app:
    cache_expire: 3600 # seconds
  admin:
    apikey: "1234567890"
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  username: ""
  connectSize: 15
  timeout: 5
etcd:
  endpoints:
    - "http://127.0.0.1:2379"
  timeout: 5
  # worker_prefix: "/go-scheduler/agent"
gateway:
  cors:
    - "localhost"
    - "127.0.0.1:8081"
    - "example.com"
  plugins:
    local:
      logger: 1
      exception: 0
      http: 2
      params_validator: 3
      auth: 4
      # only_api_key_auth: 4
    rpc:
      # - server:
      #   name: "example-server"
      #   endpoint:
      #     - addr: "127.0.0.1:21216"
      #       weight: 1
      #     - addr: "127.0.0.1:21217"
      #       weight: 2
      #   priority: 10
      #   timeout: 30
      #   lb: "round_robin"
      #   pool:
      #     max_open_conns: 100
      #     max_idle_conns: 50
      #     size: 50
      #     timeout: 10
      #     min_idle_conns: 25
      #     max_active_conns: 20
  descriptor:
    out_dir: "/tmp/begonia/descriptors"
test:
  file:
    upload:
      dir: "/tmp/upload"
    protos:
      dir: "/tmp/protos"
      desc: "/tmp/protos/api.bin"
    engines:
      - name: "FILE_ENGINE_MINIO"
        endpoint: "127.0.0.1:9000"
        accessKey: "begonia"
        secretKey: "begoniabegonia"
      - name: "FILE_ENGINE_LOCAL"
        endpoint: "/tmp/upload"
  etcd:
    endpoint:
      prefix: "/begonia/endpoints"
    app:
      prefix: "/begonia/apps"
  auth:
    aes_key: "1234567890123456"
    aes_iv: "L!#x].upV.>Jx0QN"
    jwt_secret: "WNjp6mW^GXnRf3]34asF"
    jwt_expiration: 7200 # seconds
    rsa:
      private_key: "/tmp/auth_private_key.pem"
      public_key: "/tmp/auth_public_key.pem"
  gateway:
    cors:
      - "localhost"
      - "127.0.0.1:8081"
      - "example.com"
    plugins:
      local:
        logger: 1
        exception: 0
        http: 2
        params_validator: 3
        auth: 4
        # only_api_key_auth: 4
      rpc:
        - server:
          name: "example-server"
          endpoint:
            - addr: "127.0.0.1:21216"
              weight: 1
            - addr: "127.0.0.1:21217"
              weight: 2
          priority: 10
          timeout: 30
          lb: "round_robin"
          pool:
            max_open_conns: 100
            max_idle_conns: 50
            size: 50
            timeout: 10
            min_idle_conns: 25
            max_active_conns: 20
common:
  cache_prefix_key: "begonia"
  filter_key_prefix: "filter"
  app_key_prefix: "kv:app"
  # blacklist_key_prefix: "blacklist"
  pubsub_key_prefix: "pubsub"
  multi_cache_strategy: 1
  kv_prefix: "cache"
  pubsub_key_channel: "pubsub:channel"
  etcd:
    endpoint:
      prefix: "/begonia/endpoints"
    app:
      prefix: "/begonia/apps"
