"dev":
  endpoints:
    proto:
      makefile: "/data/work/begonia-org/begonia/internal/pkg/runtime/Makefile"
      gomod: "/data/work/begonia-org/begonia/go.mod"
      wd: "/data/work/begonia-org"
    plugins:
      dir: "/data/work/begonia-org/begonia/plugins"
  file:
    upload:
      dir: /data/work/begonia-org/begonia/upload
    protos: 
      dir: /data/work/begonia-org/begonia/protos
  mysql:
    host: "127.0.0.1"
    port: 3306
    user: "test"
    password: "test"
    database: "test"
  admin:
    name: "admin"
    password: "admin"
    email: "admin@example.com"
    phone: "12345678901"
  auth:
    aes_key: "1234567890123456"
    aes_iv: "L!#x].upV.>Jx0QN"
    jwt_secret: "WNjp6mW^GXnRf3]34asF"
    jwt_expiration: 7200 # seconds
    blacklist:
      bloom:
        m: 100000
        error_rate: 0.001
      pubsub:
        channel: "gateway-blacklist"
        group: "gateway-blacklist-group"
      user:
        cache_expire: 3600 # seconds  
    app:
      cache_expire: 3600 # seconds      
  redis:
    addr: "127.0.0.1:6379"
    password: ""
    db: 0
    username: ""
    connectSize: 15
    timeout: 5
  etcd:
    endpoints:
      - "http://127.0.0.1:2379"
    timeout: 5
    worker_prefix: "/go-scheduler/agent"
  gateway:
    cors:
      - "localhost"
  common:
    rdb_key_prefix: "begonia"
    rdb_key_bloom: "begonia:bloom"
    app_key_prefix: "begonia:app"

