// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/begonia-org/begonia/internal/data"
	"github.com/begonia-org/begonia/internal/pkg/config"
	"github.com/begonia-org/begonia/internal/pkg/migrate"
	"github.com/spark-lence/tiga"
)

// Injectors from wire.go:

// }
func initOperatorApp(config2 *tiga.Configuration) *migrate.InitOperator {
	mySQLDao := data.NewMySQL(config2)
	v := migrate.NewTableModels()
	mySQLMigrate := migrate.NewMySQLMigrate(mySQLDao, v...)
	usersOperator := migrate.NewUsersOperator(mySQLDao)
	configConfig := config.NewConfig(config2)
	initOperator := migrate.NewInitOperator(mySQLMigrate, usersOperator, configConfig)
	return initOperator
}
