// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/begonia-org/begonia/internal/biz"
	"github.com/begonia-org/begonia/internal/biz/endpoint"
	"github.com/begonia-org/begonia/internal/biz/file"
	"github.com/begonia-org/begonia/internal/daemon"
	"github.com/begonia-org/begonia/internal/data"
	"github.com/begonia-org/begonia/internal/middleware"
	"github.com/begonia-org/begonia/internal/migrate"
	"github.com/begonia-org/begonia/internal/pkg/config"
	"github.com/begonia-org/begonia/internal/pkg/crypto"
	"github.com/begonia-org/begonia/internal/server"
	"github.com/begonia-org/begonia/internal/service"
	v1_2 "github.com/begonia-org/go-sdk/api/app/v1"
	v1_3 "github.com/begonia-org/go-sdk/api/endpoint/v1"
	v1_4 "github.com/begonia-org/go-sdk/api/file/v1"
	v1_5 "github.com/begonia-org/go-sdk/api/sys/v1"
	"github.com/begonia-org/go-sdk/api/user/v1"
	"github.com/begonia-org/go-sdk/logger"
	"github.com/spark-lence/tiga"
)

// Injectors from wire.go:

func InitOperatorApp(config2 *tiga.Configuration) *migrate.InitOperator {
	mySQLDao := data.NewMySQL(config2)
	v := migrate.NewTableModels()
	mySQLMigrate := migrate.NewMySQLMigrate(mySQLDao, v...)
	usersOperator := migrate.NewUsersOperator(mySQLDao)
	appOperator := migrate.NewAPPOperator(mySQLDao)
	configConfig := config.NewConfig(config2)
	initOperator := migrate.NewInitOperator(mySQLMigrate, usersOperator, appOperator, configConfig)
	return initOperator
}

func New(config2 *tiga.Configuration, log logger.Logger, endpoint2 string) GatewayWorker {
	configConfig := config.NewConfig(config2)
	mySQLDao := data.NewMySQL(config2)
	redisDao := data.NewRDB(config2)
	etcdDao := data.NewEtcd(config2)
	dataData := data.NewData(mySQLDao, redisDao, etcdDao)
	curd := data.NewCurdImpl(mySQLDao, configConfig)
	layeredCache := data.NewLayeredCache(redisDao, configConfig, log)
	appRepo := data.NewAppRepoImpl(curd, layeredCache, configConfig)
	userRepo := data.NewUserRepoImpl(dataData, layeredCache, curd, configConfig)
	authzRepo := data.NewAuthzRepoImpl(log, layeredCache)
	dataOperatorRepo := data.NewDataOperatorRepo(dataData, appRepo, userRepo, authzRepo, layeredCache, log)
	endpointRepo := data.NewEndpointRepoImpl(dataData, configConfig)
	endpointWatcher := endpoint.NewWatcher(configConfig, endpointRepo)
	dataOperatorUsecase := biz.NewDataOperatorUsecase(dataOperatorRepo, configConfig, log, endpointWatcher, endpointRepo)
	daemonDaemon := daemon.NewDaemonImpl(configConfig, dataOperatorUsecase)
	gatewayConfig := server.NewGatewayConfig(endpoint2)
	fileUsecase := file.NewFileUsecase(configConfig)
	fileServiceServer := service.NewFileService(fileUsecase, configConfig)
	usersAuth := crypto.NewUsersAuth(configConfig)
	authzUsecase := biz.NewAuthzUsecase(authzRepo, userRepo, log, usersAuth, configConfig)
	authServiceServer := service.NewAuthzService(authzUsecase, log, usersAuth, configConfig)
	endpointUsecase := endpoint.NewEndpointUsecase(endpointRepo, fileUsecase, configConfig)
	endpointServiceServer := service.NewEndpointsService(endpointUsecase, log, configConfig)
	appUsecase := biz.NewAppUsecase(appRepo, configConfig)
	appsServiceServer := service.NewAppService(appUsecase, log, configConfig)
	systemServiceServer := service.NewSysService()
	userUsecase := biz.NewUserUsecase(userRepo, configConfig)
	userServiceServer := service.NewUserService(userUsecase, log, configConfig)
	v := service.NewServices(fileServiceServer, authServiceServer, endpointServiceServer, appsServiceServer, systemServiceServer, userServiceServer)
	accessKeyAuth := biz.NewAccessKeyAuth(appRepo, configConfig, log)
	pluginsApply := middleware.New(configConfig, redisDao, authzUsecase, log, accessKeyAuth, layeredCache)
	gatewayServer := server.NewGateway(gatewayConfig, configConfig, v, pluginsApply)
	gatewayWorker := NewGatewayWorkerImpl(daemonDaemon, gatewayServer)
	return gatewayWorker
}

func NewAuthzSvr(config2 *tiga.Configuration, log logger.Logger) v1.AuthServiceServer {
	redisDao := data.NewRDB(config2)
	configConfig := config.NewConfig(config2)
	layeredCache := data.NewLayeredCache(redisDao, configConfig, log)
	authzRepo := data.NewAuthzRepoImpl(log, layeredCache)
	mySQLDao := data.NewMySQL(config2)
	etcdDao := data.NewEtcd(config2)
	dataData := data.NewData(mySQLDao, redisDao, etcdDao)
	curd := data.NewCurdImpl(mySQLDao, configConfig)
	userRepo := data.NewUserRepoImpl(dataData, layeredCache, curd, configConfig)
	usersAuth := crypto.NewUsersAuth(configConfig)
	authzUsecase := biz.NewAuthzUsecase(authzRepo, userRepo, log, usersAuth, configConfig)
	authServiceServer := service.NewAuthzService(authzUsecase, log, usersAuth, configConfig)
	return authServiceServer
}

func NewAPPSvr(config2 *tiga.Configuration, log logger.Logger) v1_2.AppsServiceServer {
	mySQLDao := data.NewMySQL(config2)
	configConfig := config.NewConfig(config2)
	curd := data.NewCurdImpl(mySQLDao, configConfig)
	redisDao := data.NewRDB(config2)
	layeredCache := data.NewLayeredCache(redisDao, configConfig, log)
	appRepo := data.NewAppRepoImpl(curd, layeredCache, configConfig)
	appUsecase := biz.NewAppUsecase(appRepo, configConfig)
	appsServiceServer := service.NewAppService(appUsecase, log, configConfig)
	return appsServiceServer
}

func NewEndpointSvr(config2 *tiga.Configuration, log logger.Logger) v1_3.EndpointServiceServer {
	mySQLDao := data.NewMySQL(config2)
	redisDao := data.NewRDB(config2)
	etcdDao := data.NewEtcd(config2)
	dataData := data.NewData(mySQLDao, redisDao, etcdDao)
	configConfig := config.NewConfig(config2)
	endpointRepo := data.NewEndpointRepoImpl(dataData, configConfig)
	fileUsecase := file.NewFileUsecase(configConfig)
	endpointUsecase := endpoint.NewEndpointUsecase(endpointRepo, fileUsecase, configConfig)
	endpointServiceServer := service.NewEndpointsService(endpointUsecase, log, configConfig)
	return endpointServiceServer
}

func NewFileSvr(config2 *tiga.Configuration, log logger.Logger) v1_4.FileServiceServer {
	configConfig := config.NewConfig(config2)
	fileUsecase := file.NewFileUsecase(configConfig)
	fileServiceServer := service.NewFileService(fileUsecase, configConfig)
	return fileServiceServer
}

func NewSysSvr(config2 *tiga.Configuration, log logger.Logger) v1_5.SystemServiceServer {
	systemServiceServer := service.NewSysService()
	return systemServiceServer
}
